require 'config/setup'
require 'config/keymaps'
require 'config/auto-commands/text-yank-post'
require('lazy').setup {
  require 'config/plugins/autopairs',
  require 'config/plugins/neo-tree',
  require 'config/plugins/git-signs',
  require 'config/plugins/guess-indent',
  require 'config/plugins/comment',
  require 'config/plugins/zen-mode',
  require 'config/plugins/which-key',
  require 'config/plugins/telescope',
  require 'config/plugins/lazydev',
  require 'config/plugins/nvim-lsp',
  require 'config/plugins/conform',
  require 'config/plugins/blink-cmp',
  require 'config/plugins/tokyo-night-theme',
  require 'config/plugins/todo-comments',
  require 'config/plugins/mini-nvim',
  require 'config/plugins/treesitter',
  require 'config/plugins/copilot-chat',
}
